#!/bin/bash
set -euo pipefail

echo "[ci_post_clone] Starting post-clone setup..."

# Ensure submodules are initialized and updated (if any)
echo "[ci_post_clone] Syncing and updating git submodules..."
if [ -f .gitmodules ]; then
  echo "[ci_post_clone] .gitmodules found. Attempting to sync and update submodules..."
  git submodule sync --recursive || echo "[ci_post_clone] Warning: submodule sync failed; continuing"
  git submodule update --init --recursive || echo "[ci_post_clone] Warning: submodule update failed; continuing"
else
  echo "[ci_post_clone] No submodules detected."
fi

# Ensure we have a predictable PATH and a local bin directory if needed
BIN_DIR="$CI_WORKSPACE/.bin"
mkdir -p "$BIN_DIR"
export PATH="$BIN_DIR:$PATH"

echo "[ci_post_clone] Checking for XcodeGen..."
if ! command -v xcodegen >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    echo "[ci_post_clone] Homebrew detected. Installing XcodeGen via brew..."
    brew update
    if ! brew list xcodegen >/dev/null 2>&1; then
      brew install xcodegen
    else
      brew upgrade xcodegen || true
    fi
  else
    echo "[ci_post_clone] Homebrew not available. XcodeGen is required to generate the project."
    echo "[ci_post_clone] Please ensure XcodeGen is available in PATH or install it here."
  fi
fi

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "[ci_post_clone] ERROR: XcodeGen not found. Cannot generate the Xcode project."
  exit 1
fi

echo "[ci_post_clone] XcodeGen version: $(xcodegen --version)"

# Generate the Xcode project from the repo root
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

# Clean any pre-existing Xcode project to avoid naming/case collisions (generated by XcodeGen below)
if [ -d "Ba6Ai.xcodeproj" ] || [ -d "Ba6ai.xcodeproj" ]; then
  echo "[ci_post_clone] Removing existing .xcodeproj to ensure a clean generate..."
  rm -rf Ba6Ai.xcodeproj Ba6ai.xcodeproj
fi

if [ -f "project.yml" ]; then
  echo "[ci_post_clone] Generating Xcode project with XcodeGen..."
  xcodegen generate --spec project.yml
  echo "[ci_post_clone] Xcode project generated."
  echo "[ci_post_clone] Listing schemes in generated project..."
  if command -v xcodebuild >/dev/null 2>&1; then
    proj=$(ls -1 *.xcodeproj | head -n 1)
    if [ -n "$proj" ]; then
      echo "[ci_post_clone] Found project: $proj"
      xcodebuild -list -project "$proj" || true
    else
      echo "[ci_post_clone] No .xcodeproj found after generation."
    fi
  fi
else
  echo "[ci_post_clone] ERROR: project.yml not found at $REPO_ROOT"
  exit 1
fi

echo "[ci_post_clone] Post-clone setup complete."
