const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const OUT_PATH = path.join(ROOT, 'env.js');

const PUBLIC_KEYS = new Set([
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
  'NEYNAR_API_KEY',
  'NEYNAR_BASE_URL',
  'NEYNAR_CLIENT_ID'
]);

if (!fs.existsSync(ENV_PATH)) {
  console.error('Missing .env file at', ENV_PATH);
  process.exit(1);
}

const content = fs.readFileSync(ENV_PATH, 'utf8');
const lines = content.split(/\r?\n/);
const env = {};

for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eq = trimmed.indexOf('=');
  if (eq === -1) continue;
  const key = trimmed.slice(0, eq).trim();
  if (!PUBLIC_KEYS.has(key)) continue;
  let value = trimmed.slice(eq + 1).trim();
  if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
    value = value.slice(1, -1);
  }
  env[key] = value;
}

const output = `// Generated by scripts/generate-env.js\nwindow.__ENV__ = ${JSON.stringify(env, null, 2)};\n`;
fs.writeFileSync(OUT_PATH, output, 'utf8');

const keys = Object.keys(env);
console.log(`env.js generated with ${keys.length} keys: ${keys.join(', ') || 'none'}`);
