const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const OUT_PATH = path.join(ROOT, 'env.js');

const PUBLIC_KEYS = new Set([
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY'
]);

const readEnvFile = () => {
  if (!fs.existsSync(ENV_PATH)) return null;
  const content = fs.readFileSync(ENV_PATH, 'utf8');
  const lines = content.split(/\r?\n/);
  const env = {};

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    if (!PUBLIC_KEYS.has(key)) continue;
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }

  return env;
};

const readProcessEnv = () => {
  const env = {};
  for (const key of PUBLIC_KEYS) {
    if (process.env[key]) env[key] = process.env[key];
  }
  return env;
};

const envFromFile = readEnvFile();
const env = envFromFile && Object.keys(envFromFile).length ? envFromFile : readProcessEnv();

if (!Object.keys(env).length) {
  console.error('No env values found. Add .env locally or set Netlify environment variables.');
  process.exit(1);
}

const output = `// Generated by scripts/generate-env.js\nwindow.__ENV__ = ${JSON.stringify(env, null, 2)};\n`;
fs.writeFileSync(OUT_PATH, output, 'utf8');

const keys = Object.keys(env);
console.log(`env.js generated with ${keys.length} keys: ${keys.join(', ') || 'none'}`);
